// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWiqQXg7cw5BMiq6Vc-OP4MEl_4tBKLwY',
    appId: '1:632278975325:web:928b297adc6246f0dfdeb4',
    messagingSenderId: '632278975325',
    projectId: 'cubesat-gs',
    authDomain: 'cubesat-gs.firebaseapp.com',
    storageBucket: 'cubesat-gs.firebasestorage.app',
    measurementId: 'G-7FSREWD640',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH8K1SYsGEW-Vu8bk0hrOniCMjwz5lQuw',
    appId: '1:632278975325:android:fa3c93189d0fc528dfdeb4',
    messagingSenderId: '632278975325',
    projectId: 'cubesat-gs',
    storageBucket: 'cubesat-gs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oyn9jmofuhvZUtKQ1VG_ce7p0MP-aXQ',
    appId: '1:632278975325:ios:e8e87eb1c7315155dfdeb4',
    messagingSenderId: '632278975325',
    projectId: 'cubesat-gs',
    storageBucket: 'cubesat-gs.firebasestorage.app',
    iosBundleId: 'com.example.mqttDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oyn9jmofuhvZUtKQ1VG_ce7p0MP-aXQ',
    appId: '1:632278975325:ios:e8e87eb1c7315155dfdeb4',
    messagingSenderId: '632278975325',
    projectId: 'cubesat-gs',
    storageBucket: 'cubesat-gs.firebasestorage.app',
    iosBundleId: 'com.example.mqttDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWiqQXg7cw5BMiq6Vc-OP4MEl_4tBKLwY',
    appId: '1:632278975325:web:0f363d903e5c6ec6dfdeb4',
    messagingSenderId: '632278975325',
    projectId: 'cubesat-gs',
    authDomain: 'cubesat-gs.firebaseapp.com',
    storageBucket: 'cubesat-gs.firebasestorage.app',
    measurementId: 'G-KJ3M1M0QK0',
  );

}